# run/ray_batch_eval_config.yaml
# Ray批量LoRA评估系统完整配置文件

# ============ 基本配置 ============
config: "/data3/user/jin509/malicious-finetuning/experiments-sft_stage-back/lm_eval_model_configs_final-debug.json"
tasks: "all"
progress_file: "/data3/user/jin509/malicious-finetuning/experiments-sft_stage-back/lm_eval_model_configs_final_progress-debug.csv"

# ============ GPU配置 ============
num_gpus: 4
tensor_parallel_size: null  # 默认等于num_gpus
gpu_memory_utilization: 0.8

# ============ Ray配置 ============
ray_address: null  # null表示本地模式，可设置为 "ray://head_node_ip:10001" 连接集群

# ============ 运行模式 ============
force_rerun: false          # 强制重跑所有任务
retry_failed_only: false    # 只重试失败任务
show_progress: false        # 只显示进度，不执行评测

# ============ 环境变量配置 ============
environment_variables:
  # HuggingFace 缓存配置
  # TODO 修改这里
  HF_HOME: "/data3/user/jin509/new_hf_cache"
  HF_DATASETS_CACHE: "/data3/user/jin509/new_hf_cache/datasets"
  HUGGINGFACE_HUB_CACHE: "/data3/user/jin509/new_hf_cache"
  
  # 离线模式配置
  HF_DATASETS_OFFLINE: "1"
  TRANSFORMERS_OFFLINE: "1"
  HF_HUB_OFFLINE: "1"
  HF_HUB_DISABLE_TELEMETRY: "1"
  HF_ALLOW_CODE_EVAL: "1"
  
  # 其他可选配置
  TOKENIZERS_PARALLELISM: "false"
  CUDA_LAUNCH_BLOCKING: "1"
  VLLM_WORKER_MULTIPROC_METHOD: "spawn"
  

# ============ 高级配置（可选） ============
# 批处理配置
batch_processing:
  max_concurrent_multiplier: null
  timeout_seconds: 3600         # 单个任务超时时间（秒）
  
# 日志配置
logging:
  level: "INFO"                 # 日志级别: DEBUG, INFO, WARNING, ERROR
  save_detailed_logs: true      # 是否保存详细日志
  
# 资源管理
resource_management:
  auto_cleanup: true            # 自动清理Ray Actor
  memory_cleanup_interval: 10   # 内存清理间隔（任务数）













# ============ 使用说明 ============
# 使用方法:
# 1. 基本用法：
#    python run/ray_batch_eval.py --yaml-config run/ray_batch_eval_config.yaml
#
# 2. 覆盖特定参数：
#    python run/ray_batch_eval.py --yaml-config run/ray_batch_eval_config.yaml --num-gpus 2
#
# 3. 只查看进度：
#    python run/ray_batch_eval.py --yaml-config run/ray_batch_eval_config.yaml --show-progress
#
# 4. 只重试失败任务：
#    python run/ray_batch_eval.py --yaml-config run/ray_batch_eval_config.yaml --retry-failed-only
#
# 注意：
# - 命令行参数的优先级高于YAML配置
# - 环境变量会自动传递给所有Worker进程
# - 路径建议使用绝对路径以避免问题